compile tests with ts
wassertim/vexflow pull request #2
Opened 2021-03-22 20:30 UTC by wassertim

2021-03-22 21:37 UTC, rvilarl commented
@wassertim I suggest to push the releases files without change in order to reduce the number of changes shown in the PR. This number if it is big (you have more than 46000 deletions) has a negative impact in reviewers.

2021-03-22 22:21 UTC, rvilarl requested changes

2021-03-22 22:21 UTC, rvilarl commented on tsconfig.json
> +  "exclude": [
I suggest to remove the excludes here, they compete with the definitions in Gruntfile.

2021-03-22 22:21 UTC, rvilarl commented on tsconfig.json
> +  "include": [
I suggest ot remove the includes here, they compete with the definitions in Gruntfile

2021-03-22 22:21 UTC, rvilarl commented on tsconfig.json
> +    "strict": false,
I believe that compiling the tests with strict will be very challenging. Is there a possibility to leave it in the src and remove it on the tests?

2021-03-22 22:21 UTC, rvilarl commented on tsconfig.json
> +    "target": "ES5",
I suggest to keep the same order as the original tsconfig to facilitate review.

2021-03-22 22:21 UTC, rvilarl commented on tsconfig.json
> +    "target": "ES5",
I would say that allowJS should be required. If the other ones in this file are required, I do not know.

2021-03-22 22:21 UTC, rvilarl commented on tools/generate_png_images.js
> +VF._fs = fs;
What is the difference between VF._fs and VF.fs?

2021-03-22 22:21 UTC, rvilarl commented on tests/music_tests.ts
> +declare const VF: any;
This declarations VF: any does not allow eslint to make any type check. It would be nice to have the imports.

2021-03-22 22:21 UTC, rvilarl commented on tests/music_tests.ts
>  VF.Test.Music = (function () {
Is there any benefit on having a structure compared to a class. And a function returning a var with several functions. I do not understand the aim, do you?

2021-03-22 22:21 UTC, rvilarl commented on Gruntfile.js
> +const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
Is this plugin being used?

2021-03-22 22:21 UTC, rvilarl commented on Gruntfile.js
> +  grunt.registerTask('default', ['eslint', 'webpack:buildDev', 'webpack:buildTest', 'webpack:buildNode', 'docco']);
I believe it is a good idea to start with 'clean' to avoid rests from other builds. ie.: ['clean', 'eslint'....

2021-03-22 22:21 UTC, rvilarl commented on Gruntfile.js
> +  grunt.registerTask('test', 'Run qunit tests.', ['webpack:buildDev', 'webpack:buildTest', 'webpack:buildNode', 'qunit']);
I believe it is a good idea to start with 'clean' to avoid rests from other builds. ie.: ['clean', 'webpack:buildDev'....

2021-03-22 22:21 UTC, rvilarl commented on package.json
> +    "tsconfig-paths-webpack-plugin": "^3.5.1",
As above, is that needed?

2021-03-23 08:02 UTC, wassertim commented on tests/gracenote_tests.js
> +      vf.Formatter().joinVoices([voice]).formatToStave([voice], stave);
I need to investigate about it. The compiler complained about it, that is why I deleted it

2021-03-23 08:03 UTC, wassertim commented on tsconfig.json
> +    "strict": false,
Why not solve strict when we are in typescript entirely?

2021-03-23 08:04 UTC, wassertim commented on tsconfig.json
> +    "strict": false,
We should remember our priority here, which is typescript migration only. If we solve one problem at a time, we will be faster

2021-03-23 08:06 UTC, wassertim commented on Gruntfile.js
> +const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
Yes, It is used for resolving paths

2021-03-23 08:06 UTC, wassertim commented on Gruntfile.js
> +  grunt.registerTask('default', ['eslint', 'webpack:buildDev', 'webpack:buildTest', 'webpack:buildNode', 'docco']);
yes, it is a good idea. I agree

2021-03-23 08:59 UTC, rvilarl commented on Gruntfile.js
> +const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
which paths? the project is compiled on a single js file.

2021-03-23 09:00 UTC, rvilarl commented on tsconfig.json
> +    "strict": false,
well I think it is easier to adap it one by one

2021-03-23 10:14 UTC, rvilarl commented on tsconfig.json
> +    "strict": false,
Anyway I am open to do it in another way

2021-03-23 19:23 UTC, wassertim commented
> @wassertim I suggest to push the releases files without change in order to reduce the number of changes shown in the PR. This number if it is big (you have more than 46000 deletions) has a negative impact in reviewers.

Yes I mistakenly removed it. I will add them back. Anyway it will be different files because we have chunks here

2021-03-23 19:52 UTC, wassertim commented on tests/annotation_tests.js
> +      var ctx = contextBuilder(options.elementId, 600, 200);
Yes, it makes sense to resolve it separately. I will do it

2021-03-23 19:55 UTC, wassertim commented on tests/gracenote_tests.js
> +      vf.Formatter().joinVoices([voice]).formatToStave([voice], stave);
So in this case it is like this
```ts
const vf: Factory = makeFactory();
vf.Formatter() // Formatter is just a method and not a constructor, you can take a look in Factory.js
```

2021-03-23 19:58 UTC, wassertim commented on tests/gracenote_tests.js
> +      vf.Formatter().joinVoices([voice]).formatToStave([voice], stave);
don't mix with `VF.Formatter`. In this case `Formatter is a class`

2021-03-23 21:28 UTC, rvilarl commented on tests/gracenote_tests.js
> +      vf.Formatter().joinVoices([voice]).formatToStave([voice], stave);
sorry I did not see that

2021-04-02 09:47 UTC, wassertim commented on tests/music_tests.ts
> +declare const VF: any;
Once we have it as a module we will introduce it here

2021-04-02 15:20 UTC, merged